Fixed the following item  in SplashScreenActivity.java removed the use of Thread.stop() as it is a deprecated method and added a safe stop method  added a try catch block in the Receiver class to fix this error:
Exception: Calling startActivity() from outside of an Activity
context requires the FLAG_ACTIVITY_NEW_TASK flas. Is this really what you want?